### ISSUE TITLE
hi dev,could update the newest russellcoind 2.3 src?needed~ for a pool

### ISSUE THREAD

**Issue by 631250005** [russellcoin/src#1]
hi dev,could update the newest russellcoind 2.3 src?
needed~

**Comment by 631250005** [comment]
total center coin。。。 scam project，dev not update 2.3src

**Comment by russellcoinpay** [comment]
> total center coin。。。 scam project，dev not update 2.3src

Hi,you can use https://github.com/russellcoinpay/russellcoin

**Comment by russellcoinpay** [comment]
> total center coin。。。 scam project，dev not update 2.3src

We don't have a good developer, we are trying to migrate the Russell coin to the latest version of Shike.
